version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/paws
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
