# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build step complete

artifacts:
  files:
    - '**/*'
