version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - echo Build completed.
      - ls -la  # For debugging

artifacts:
  files:
    - appspec.yml  # THIS WAS MISSING - ADD IT FIRST
    - app.py
    - app.wsgi
    - requirements.txt
    - package/**
    - templates/**
    - static/**
    - scripts/**
    - .ebextensions/**
  discard-paths: no
