version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - app.py
    - app.wsgi
    - requirements.txt
    - package/**
    - templates/**
    - static/**
    - scripts/**               # If you have helper deployment scripts
    - .ebextensions/**         # If using any environment configs
  discard-paths: no
